/* ════════════════════════════════════════════════════════
   QR-LABEL - getrouwe weergave van het gegenereerde QR-label
   uit de app (DIGITAAL LOGBOEK + scan-stappen + Project-ID +
   PIN + merkmark). Gebruikt op de homepage-band en printpagina.
   ════════════════════════════════════════════════════════ */

export default function QrLabel({ className = "" }: { className?: string }) {
  return (
    <div
      className={[
        "w-full max-w-[440px] rounded-[16px] border border-border bg-white p-5 md:p-6",
        className,
      ].join(" ")}
      style={{ boxShadow: "0 30px 60px -24px rgba(13,15,26,0.30)" }}
    >
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-brand-orange">
            Digitaal logboek
          </div>
          <h3 className="mt-1.5 text-[15px] font-black leading-[1.2] tracking-[-0.01em] text-brand-blue md:text-[16px]">
            Raadpleeg documenten, mutaties en handleidingen
          </h3>

          <ol className="mt-3 flex flex-col gap-1.5 text-[12px] leading-[1.4] text-ink">
            <li className="flex gap-2">
              <span className="font-bold text-brand-orange">1.</span>
              Scan de QR-code
            </li>
            <li className="flex gap-2">
              <span className="font-bold text-brand-orange">2.</span>
              <span>
                Of ga naar:{" "}
                <span className="break-all font-mono text-[11px] font-bold text-brand-blue">
                  installatiedossier.nl/p/rijksmuseum-j74fyi
                </span>
              </span>
            </li>
            <li className="flex gap-2">
              <span className="font-bold text-brand-orange">3.</span>
              <span>
                Project-ID:{" "}
                <span className="font-mono text-[11px] font-bold text-ink">
                  rijksmuseum-j74fyi
                </span>{" "}
                · PIN:{" "}
                <span className="font-mono text-[11px] font-bold text-brand-orange">
                  392257
                </span>
              </span>
            </li>
          </ol>
        </div>

        {/* QR */}
        <div className="flex-shrink-0">
          <QrSvg className="h-[116px] w-[116px] md:h-[132px] md:w-[132px]" />
        </div>
      </div>

      {/* Merkmark */}
      <div className="mt-4 flex items-center justify-between border-t border-border pt-3">
        <div className="flex items-center gap-2">
          <BrandMark />
          <div className="leading-tight">
            <div className="text-[12px] font-black text-ink">
              Installatie dossier
            </div>
            <div className="text-[11px] font-bold text-brand-blue">
              Rijksmuseum
            </div>
          </div>
        </div>
        <div className="font-mono text-[8px] uppercase tracking-wide text-gray-lt">
          Generated by Installatiedossier
        </div>
      </div>
    </div>
  );
}

/* Merk-mark: 2x2 raster van afgeronde vierkanten (3 blauw, 1 oranje) */
function BrandMark() {
  return (
    <span className="grid flex-shrink-0 grid-cols-2 gap-0.5">
      <span className="block h-2.5 w-2.5 rounded-[2px] bg-brand-blue" />
      <span className="block h-2.5 w-2.5 rounded-[2px] bg-brand-blue" />
      <span className="block h-2.5 w-2.5 rounded-[2px] bg-brand-orange" />
      <span className="block h-2.5 w-2.5 rounded-[2px] bg-brand-blue" />
    </span>
  );
}

/* Brand-QR (gestileerd, zelfde patroon als in de app-mockups) */
function QrSvg({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 21 21"
      shapeRendering="crispEdges"
      className={className}
      aria-hidden="true"
    >
      <rect width="21" height="21" fill="#fff" />
      <g fill="#0D0F1A">
        <rect x="0" y="0" width="5" height="5" />
        <rect x="1" y="1" width="3" height="3" fill="#fff" />
        <rect x="2" y="2" width="1" height="1" />
        <rect x="16" y="0" width="5" height="5" />
        <rect x="17" y="1" width="3" height="3" fill="#fff" />
        <rect x="18" y="2" width="1" height="1" />
        <rect x="0" y="16" width="5" height="5" />
        <rect x="1" y="17" width="3" height="3" fill="#fff" />
        <rect x="2" y="18" width="1" height="1" />
        <rect x="7" y="2" width="1" height="1" />
        <rect x="9" y="3" width="1" height="1" />
        <rect x="11" y="2" width="1" height="1" />
        <rect x="13" y="3" width="1" height="1" />
        <rect x="6" y="6" width="2" height="2" />
        <rect x="10" y="7" width="1" height="2" />
        <rect x="12" y="6" width="2" height="1" />
        <rect x="7" y="9" width="2" height="1" />
        <rect x="10" y="10" width="2" height="1" />
        <rect x="13" y="9" width="1" height="2" />
        <rect x="7" y="12" width="1" height="2" />
        <rect x="9" y="13" width="2" height="1" />
        <rect x="12" y="12" width="2" height="2" />
        <rect x="7" y="15" width="2" height="1" />
        <rect x="10" y="16" width="1" height="2" />
        <rect x="13" y="15" width="1" height="1" />
        <rect x="15" y="13" width="1" height="2" />
        <rect x="17" y="14" width="2" height="1" />
        <rect x="15" y="17" width="2" height="1" />
        <rect x="18" y="17" width="1" height="2" />
      </g>
      <rect x="9" y="9" width="3" height="3" fill="#E8692C" />
    </svg>
  );
}
